// Canonical AG-UI EventType enum mirror, pinned to the @ag-ui/core
// definition documented in docs/VERIFICATION.md.
// Source of truth: ag-ui-protocol/ag-ui main @ sdks/typescript/packages/core/src/events.ts
//
// BREAKING CHANGE (v0.2.0): Standardized on Python's run lifecycle vocabulary
// - RUN_COMPLETED/RUN_FAILED/RUN_CANCELLED (more precise than FINISHED/ERROR)
// - RUN_FINISHED and RUN_ERROR kept as deprecated aliases until v0.3.0
// - See docs/SCHEMA_AUDIT_REPORT.md Risk 0 for details

export enum AGUIEventType {
  // ----- Messages -----
  TEXT_MESSAGE_START = 'TEXT_MESSAGE_START',
  TEXT_MESSAGE_CONTENT = 'TEXT_MESSAGE_CONTENT',
  TEXT_MESSAGE_END = 'TEXT_MESSAGE_END',
  TEXT_MESSAGE_CHUNK = 'TEXT_MESSAGE_CHUNK',
  MESSAGE = 'MESSAGE',
  MESSAGE_CHUNK = 'MESSAGE_CHUNK',
  
  // ----- Tool calls -----
  TOOL_CALL = 'TOOL_CALL',
  TOOL_CALL_START = 'TOOL_CALL_START',
  TOOL_CALL_ARGS = 'TOOL_CALL_ARGS',
  TOOL_CALL_END = 'TOOL_CALL_END',
  TOOL_CALL_CHUNK = 'TOOL_CALL_CHUNK',
  TOOL_CALL_RESULT = 'TOOL_CALL_RESULT',
  TOOL_CALL_ERROR = 'TOOL_CALL_ERROR',
  TOOL_END = 'TOOL_END',
  
  // ----- State -----
  STATE_SNAPSHOT = 'STATE_SNAPSHOT',
  STATE_DELTA = 'STATE_DELTA',
  MESSAGES_SNAPSHOT = 'MESSAGES_SNAPSHOT',
  ACTIVITY_SNAPSHOT = 'ACTIVITY_SNAPSHOT',
  ACTIVITY_DELTA = 'ACTIVITY_DELTA',
  
  // ----- Run lifecycle -----
  RUN_STARTED = 'RUN_STARTED',
  RUN_COMPLETED = 'RUN_COMPLETED',
  RUN_FAILED = 'RUN_FAILED',
  RUN_CANCELLED = 'RUN_CANCELLED',
  
  /** @deprecated Use RUN_COMPLETED - removed in v0.3.0 */
  RUN_FINISHED = 'RUN_COMPLETED',
  /** @deprecated Use RUN_FAILED - removed in v0.3.0 */
  RUN_ERROR = 'RUN_FAILED',
  
  // ----- Step lifecycle -----
  STEP_STARTED = 'STEP_STARTED',
  STEP_COMPLETED = 'STEP_COMPLETED',
  STEP_FAILED = 'STEP_FAILED',
  STEP_FINISHED = 'STEP_FINISHED',
  
  // ----- Agent lifecycle -----
  AGENT_START = 'AGENT_START',
  AGENT_END = 'AGENT_END',
  
  // ----- Node lifecycle -----
  NODE_STARTED = 'NODE_STARTED',
  NODE_UPDATE = 'NODE_UPDATE',
  NODE_FAILED = 'NODE_FAILED',
  
  // ----- Handoffs -----
  HANDOFF = 'HANDOFF',
  
  // ----- SwarmGraph insight -----
  SWARMGRAPH_TOPOLOGY = 'SWARMGRAPH_TOPOLOGY',
  SWARMGRAPH_CONSENSUS = 'SWARMGRAPH_CONSENSUS',
  SWARMGRAPH_COST = 'SWARMGRAPH_COST',
  
  // ----- Human-in-the-loop -----
  HITL_PROMPT = 'HITL_PROMPT',
  HITL_RESPONSE = 'HITL_RESPONSE',
  HITL_TIMEOUT = 'HITL_TIMEOUT',
  
  // ----- Cockpit contract lifecycle -----
  CONTRACT_PROPOSED = 'CONTRACT_PROPOSED',
  CONTRACT_ACCEPTED = 'CONTRACT_ACCEPTED',
  CONTRACT_FULFILLED = 'CONTRACT_FULFILLED',
  CONTRACT_VIOLATED = 'CONTRACT_VIOLATED',
  RECEIPT_GENERATED = 'RECEIPT_GENERATED',
  FAILURE_AUTOPSY_GENERATED = 'FAILURE_AUTOPSY_GENERATED',
  EVIDENCE_REF_CREATED = 'EVIDENCE_REF_CREATED',
  
  // ----- Reasoning (existing) -----
  REASONING_START = 'REASONING_START',
  REASONING_MESSAGE_START = 'REASONING_MESSAGE_START',
  REASONING_MESSAGE_CONTENT = 'REASONING_MESSAGE_CONTENT',
  REASONING_MESSAGE_END = 'REASONING_MESSAGE_END',
  REASONING_MESSAGE_CHUNK = 'REASONING_MESSAGE_CHUNK',
  REASONING_END = 'REASONING_END',
  REASONING_ENCRYPTED_VALUE = 'REASONING_ENCRYPTED_VALUE',
  
  // ----- Raw / fallback -----
  RAW = 'RAW',
  CUSTOM = 'CUSTOM',
}

export const RUN_LIFECYCLE_EVENTS = new Set<AGUIEventType>([
  AGUIEventType.RUN_STARTED,
  AGUIEventType.RUN_COMPLETED,
  AGUIEventType.RUN_FAILED,
  AGUIEventType.RUN_CANCELLED,
]);
