// Canonical AG-UI EventType enum mirror, pinned to the @ag-ui/core
// definition documented in docs/VERIFICATION.md.
// Source of truth: ag-ui-protocol/ag-ui main @ sdks/typescript/packages/core/src/events.ts
//
// BREAKING CHANGE (v0.2.0): Standardized on Python's run lifecycle vocabulary
// - RUN_COMPLETED/RUN_FAILED/RUN_CANCELLED (more precise than FINISHED/ERROR)
// - RUN_FINISHED and RUN_ERROR kept as deprecated aliases until v0.3.0
// - See docs/SCHEMA_AUDIT_REPORT.md Risk 0 for details

export enum AGUIEventType {
  TEXT_MESSAGE_START = 'TEXT_MESSAGE_START',
  TEXT_MESSAGE_CONTENT = 'TEXT_MESSAGE_CONTENT',
  TEXT_MESSAGE_END = 'TEXT_MESSAGE_END',
  TEXT_MESSAGE_CHUNK = 'TEXT_MESSAGE_CHUNK',
  TOOL_CALL_START = 'TOOL_CALL_START',
  TOOL_CALL_ARGS = 'TOOL_CALL_ARGS',
  TOOL_CALL_END = 'TOOL_CALL_END',
  TOOL_CALL_CHUNK = 'TOOL_CALL_CHUNK',
  TOOL_CALL_RESULT = 'TOOL_CALL_RESULT',
  STATE_SNAPSHOT = 'STATE_SNAPSHOT',
  STATE_DELTA = 'STATE_DELTA',
  MESSAGES_SNAPSHOT = 'MESSAGES_SNAPSHOT',
  ACTIVITY_SNAPSHOT = 'ACTIVITY_SNAPSHOT',
  ACTIVITY_DELTA = 'ACTIVITY_DELTA',
  RAW = 'RAW',
  CUSTOM = 'CUSTOM',
  
  // Run lifecycle - standardized on Python vocabulary (v0.2.0)
  RUN_STARTED = 'RUN_STARTED',
  RUN_COMPLETED = 'RUN_COMPLETED',
  RUN_FAILED = 'RUN_FAILED',
  RUN_CANCELLED = 'RUN_CANCELLED',
  
  /** @deprecated Use RUN_COMPLETED - removed in v0.3.0 */
  RUN_FINISHED = 'RUN_COMPLETED',
  /** @deprecated Use RUN_FAILED - removed in v0.3.0 */
  RUN_ERROR = 'RUN_FAILED',
  
  STEP_STARTED = 'STEP_STARTED',
  STEP_FINISHED = 'STEP_FINISHED',
  REASONING_START = 'REASONING_START',
  REASONING_MESSAGE_START = 'REASONING_MESSAGE_START',
  REASONING_MESSAGE_CONTENT = 'REASONING_MESSAGE_CONTENT',
  REASONING_MESSAGE_END = 'REASONING_MESSAGE_END',
  REASONING_MESSAGE_CHUNK = 'REASONING_MESSAGE_CHUNK',
  REASONING_END = 'REASONING_END',
  REASONING_ENCRYPTED_VALUE = 'REASONING_ENCRYPTED_VALUE',
}

export const RUN_LIFECYCLE_EVENTS = new Set<AGUIEventType>([
  AGUIEventType.RUN_STARTED,
  AGUIEventType.RUN_COMPLETED,
  AGUIEventType.RUN_FAILED,
  AGUIEventType.RUN_CANCELLED,
]);
