//! arc-protocol-rs — Sprint 1 typed protocol bridge.
//!
//! Ground truth: `protocol/fixtures/**` and `docs/schemas/*.json` generated by
//! `scripts/generate-schemas.py` from the Pydantic models in
//! `python/src/agent_runtime_cockpit/protocol/` (canonical module:
//! `event_envelope.py`; `envelope.py` is a deprecation shim — never mirror the shim).
//!
//! Additive-protocol rules enforced in types:
//! - unknown fields are *retained* (flattened `extra` maps), never rejected;
//! - unknown event kinds decode to [`KnownRunEvent::Unknown`], never an error;
//! - nothing here renames or removes any wire field.

pub mod envelope;
pub mod notification;
pub mod run_event;

pub use envelope::{ArcEnvelope, ArcError, ArcMeta};
pub use notification::DaemonNotification;
pub use run_event::{KnownRunEvent, RunEvent};
