"""Advisory Android compliance artifact generators.

Generates AndroidManifest permission fragments and Data Safety notes from a
MobileRuntimeManifest. Output is ADVISORY ONLY — requires human review
before Google Play submission.
"""

from __future__ import annotations

from typing import Any

from ..models import MobileRuntimeManifest

_ANDROID_PERMISSION_MAP: dict[str, str] = {
    "android.CAMERA": "android.permission.CAMERA",
    "android.RECORD_AUDIO": "android.permission.RECORD_AUDIO",
    "android.ACCESS_FINE_LOCATION": "android.permission.ACCESS_FINE_LOCATION",
    "android.ACCESS_COARSE_LOCATION": "android.permission.ACCESS_COARSE_LOCATION",
    "android.READ_CALENDAR": "android.permission.READ_CALENDAR",
    "android.WRITE_CALENDAR": "android.permission.WRITE_CALENDAR",
    "android.READ_CONTACTS": "android.permission.READ_CONTACTS",
    "android.WRITE_CONTACTS": "android.permission.WRITE_CONTACTS",
    "android.READ_MEDIA_IMAGES": "android.permission.READ_MEDIA_IMAGES",
    "android.READ_EXTERNAL_STORAGE": "android.permission.READ_EXTERNAL_STORAGE",
    "android.POST_NOTIFICATIONS": "android.permission.POST_NOTIFICATIONS",
}

_ADVISORY_COMMENT = (
    "<!-- ADVISORY: Generated by ARC Mobile Runtime compliance tooling. "
    "Requires human review before Google Play submission. -->"
)


def generate_manifest_permissions(manifest: MobileRuntimeManifest) -> str:
    """Return an advisory AndroidManifest.xml permission fragment."""
    perms: list[str] = []
    for cap in manifest.capabilities:
        for perm in cap.required_permissions:
            android_perm = _ANDROID_PERMISSION_MAP.get(perm.id)
            if android_perm and android_perm not in perms:
                perms.append(android_perm)

    entries = "\n".join(f'    <uses-permission android:name="{p}" />' for p in sorted(perms))
    return f"""{_ADVISORY_COMMENT}
<!-- Add these permissions to your AndroidManifest.xml <manifest> element -->
<!-- REVIEW REQUIRED: Remove any permissions your app does not actually need -->
{entries if entries else "    <!-- No dangerous permissions required by current capabilities -->"}
"""


def generate_data_safety_notes(manifest: MobileRuntimeManifest) -> dict[str, Any]:
    """Return advisory Data Safety form notes as a dict."""
    sensitive_caps = [
        c for c in manifest.capabilities if c.data_sensitivity.value in ("high", "critical")
    ]
    return {
        "advisory": True,
        "requires_human_review": True,
        "manifest_id": manifest.id,
        "data_collected": [
            {
                "capability": c.id,
                "sensitivity": c.data_sensitivity.value,
                "reads": c.reads,
                "writes": c.writes,
                "note": "[REVIEW REQUIRED] Verify what data is actually collected and why.",
            }
            for c in sensitive_caps
        ],
        "data_shared": [],
        "note": (
            "Complete this form manually in the Google Play Console. "
            "ARC-generated notes are a starting point only."
        ),
    }
