"""Advisory iOS compliance artifact generators.

Generates PrivacyInfo.xcprivacy and NSUsageDescription strings from a
MobileRuntimeManifest. Output is ADVISORY ONLY — requires human review
before App Store submission.

Reference: https://developer.apple.com/documentation/bundleresources/privacy-manifest-files
"""

from __future__ import annotations

from typing import Any

from ..models import MobileRuntimeManifest

# Map ARC permission IDs → NSPrivacyAccessedAPITypes and usage description keys
_IOS_PERMISSION_MAP: dict[str, dict[str, str]] = {
    "ios.camera": {
        "usage_key": "NSCameraUsageDescription",
        "privacy_type": "NSPrivacyAccessedAPICategoryCamera",
    },
    "ios.microphone": {
        "usage_key": "NSMicrophoneUsageDescription",
        "privacy_type": "NSPrivacyAccessedAPICategoryMicrophone",
    },
    "ios.location.whenInUse": {
        "usage_key": "NSLocationWhenInUseUsageDescription",
        "privacy_type": "NSPrivacyAccessedAPICategoryLocationWhenInUse",
    },
    "ios.location.always": {
        "usage_key": "NSLocationAlwaysUsageDescription",
        "privacy_type": "NSPrivacyAccessedAPICategoryLocationAlways",
    },
    "ios.calendars": {
        "usage_key": "NSCalendarsUsageDescription",
        "privacy_type": "NSPrivacyAccessedAPICategoryCalendars",
    },
    "ios.contacts": {
        "usage_key": "NSContactsUsageDescription",
        "privacy_type": "NSPrivacyAccessedAPICategoryContacts",
    },
    "ios.photoLibrary": {
        "usage_key": "NSPhotoLibraryUsageDescription",
        "privacy_type": "NSPrivacyAccessedAPICategoryPhotoLibrary",
    },
    "ios.photoLibraryAddUsage": {
        "usage_key": "NSPhotoLibraryAddUsageDescription",
        "privacy_type": "NSPrivacyAccessedAPICategoryPhotoLibraryAdd",
    },
}

_ADVISORY_BANNER = (
    "<!-- ADVISORY: This file was generated by ARC Mobile Runtime compliance tooling. "
    "It requires human review and must be verified by a qualified reviewer before "
    "App Store submission. ARC does not provide legal advice. -->"
)


def generate_usage_strings(manifest: MobileRuntimeManifest) -> dict[str, str]:
    """Return a dict of NSUsageDescription key → placeholder description string.

    The placeholder descriptions must be replaced with accurate, user-facing
    explanations before submission.
    """
    strings: dict[str, str] = {}
    for cap in manifest.capabilities:
        for perm in cap.required_permissions:
            perm_id = perm.id
            mapping = _IOS_PERMISSION_MAP.get(perm_id)
            if mapping and mapping["usage_key"] not in strings:
                strings[mapping["usage_key"]] = (
                    f"[REVIEW REQUIRED] {cap.name}: {cap.description or 'Describe why this permission is needed.'}"
                )
    return strings


def generate_privacy_manifest(manifest: MobileRuntimeManifest) -> str:
    """Generate an advisory PrivacyInfo.xcprivacy plist XML from a manifest.

    Returns XML string. ADVISORY ONLY — requires human review.
    """
    # Collect unique privacy types
    privacy_types: list[str] = []
    for cap in manifest.capabilities:
        for perm in cap.required_permissions:
            mapping = _IOS_PERMISSION_MAP.get(perm.id)
            if mapping and mapping["privacy_type"] not in privacy_types:
                privacy_types.append(mapping["privacy_type"])

    # Build NSPrivacyAccessedAPITypes array
    type_entries = "\n".join(
        f"        <dict>\n"
        f"            <key>NSPrivacyAccessedAPIType</key>\n"
        f"            <string>{pt}</string>\n"
        f"            <key>NSPrivacyAccessedAPITypeReasons</key>\n"
        f"            <array><string>[REVIEW REQUIRED: specify reason code]</string></array>\n"
        f"        </dict>"
        for pt in privacy_types
    )

    # Build NSPrivacyCollectedDataTypes (placeholder)
    collected_entries = (
        "        <!-- REVIEW REQUIRED: Add collected data types if any data is collected -->"
    )

    plist = f"""{_ADVISORY_BANNER}
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
    "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>NSPrivacyAccessedAPITypes</key>
    <array>
{type_entries}
    </array>
    <key>NSPrivacyCollectedDataTypes</key>
    <array>
{collected_entries}
    </array>
    <key>NSPrivacyTracking</key>
    <false/>
    <key>advisory</key>
    <true/>
    <key>requires_human_review</key>
    <true/>
</dict>
</plist>"""
    return plist


def compliance_report(manifest: MobileRuntimeManifest) -> dict[str, Any]:
    """Return a structured advisory report for iOS compliance."""
    return {
        "advisory": True,
        "requires_human_review": True,
        "manifest_id": manifest.id,
        "usage_strings": generate_usage_strings(manifest),
        "privacy_manifest_xml": generate_privacy_manifest(manifest),
        "note": (
            "All artifacts are advisory only. Review with a qualified iOS developer "
            "before App Store submission."
        ),
    }
