"""Advisory app-store review notes generator."""

from __future__ import annotations

from ..models import MobileRuntimeManifest

_BANNER = (
    "ADVISORY: Generated by ARC Mobile Runtime compliance tooling. "
    "Requires human review and legal sign-off before app-store submission."
)


def generate_review_notes(manifest: MobileRuntimeManifest) -> str:
    """Generate human-readable app review notes from a manifest."""
    lines = [
        _BANNER,
        "",
        f"App: {manifest.name} ({manifest.id} v{manifest.version})",
        f"Runtime mode: {'Simulator/mock' if manifest.simulator_mode else 'Native'}",
        "",
        "Capability summary for reviewers:",
    ]
    for cap in manifest.capabilities:
        perms = ", ".join(p.id for p in cap.required_permissions) or "none"
        lines.append(
            f"  - {cap.name} [{cap.id}]"
            f"\n    Sensitivity: {cap.data_sensitivity.value}"
            f"\n    Approval: {cap.approval_mode.value}"
            f"\n    Permissions: {perms}"
            f"\n    Reads: {cap.reads}  Writes: {cap.writes}"
            f"\n    Background: {cap.background}  Network: {cap.network}"
            f"\n    Description: {cap.description or 'N/A'}"
        )
    lines += [
        "",
        "REVIEW REQUIRED: Verify all permission usage descriptions, data collection",
        "disclosures, and consent flows before submission.",
    ]
    return "\n".join(lines)
