"""ARC standard error codes."""
from enum import Enum


class ArcErrorCode(str, Enum):
    WORKSPACE_NOT_FOUND = "WORKSPACE_NOT_FOUND"
    NO_RUNTIME_DETECTED = "NO_RUNTIME_DETECTED"
    ADAPTER_ERROR = "ADAPTER_ERROR"
    ADAPTER_NOT_SUPPORTED = "ADAPTER_NOT_SUPPORTED"
    SCHEMA_EXPORT_FAILED = "SCHEMA_EXPORT_FAILED"
    WORKFLOW_EXPORT_FAILED = "WORKFLOW_EXPORT_FAILED"
    RUN_FAILED = "RUN_FAILED"
    RUN_NOT_FOUND = "RUN_NOT_FOUND"
    CONTEXT_PROVIDER_ERROR = "CONTEXT_PROVIDER_ERROR"
    CONFORMANCE_FAILED = "CONFORMANCE_FAILED"
    INVALID_INPUT = "INVALID_INPUT"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    TIMEOUT = "TIMEOUT"
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"
